name: GitHub Actions Cron Bot

on:
  schedule:
    - cron: '9 20 * * *'
#  push:
#    branches:
#      - master

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: install
        run: yarn

      - name: node debug.js
        run: node debug.js
        env:
          TG_DEV_BOT_TOKEN: ${{ secrets.TG_DEV_BOT_TOKEN }}
          TG_DEV_CHAT_ID: ${{ secrets.TG_DEV_CHAT_ID }}
